#!/usr/bin/env bash
# Creates the Secrets the Helm chart expects. Secrets are never generated by
# the chart itself so that Argo CD does not rotate them on every sync.
#
# Usage:
#   NAMESPACE=voice-avatar-assistant scripts/create-secrets.sh
#
# Every value can be preset through the environment (see the variables below), or put
# in one KEY=value file and passed as SECRETS_FILE=<path> (template: secrets.env.example
# in the repository root). Existing secrets are kept unless FORCE=1 is set (which also
# regenerates every password) or REFRESH lists the secrets to rewrite, for example
# REFRESH=assistant-integrations after changing an API key in the file.
set -euo pipefail

NS="${NAMESPACE:-voice-avatar-assistant}"
# existing <secret> <key>: the current value in the cluster, so a refresh keeps generated
# passwords and the n8n encryption key instead of replacing them
existing() { oc get secret "$1" -n "${NS}" -o jsonpath="{.data.$2}" 2>/dev/null | base64 -d 2>/dev/null || true; }
if [ -n "${SECRETS_FILE:-}" ]; then
  [ -r "${SECRETS_FILE}" ] || { echo "SECRETS_FILE ${SECRETS_FILE} is not readable"; exit 1; }
  set -a
  # shellcheck disable=SC1090
  . "${SECRETS_FILE}"
  set +a
  echo "loaded ${SECRETS_FILE}"
fi
rand() { openssl rand -hex "${1:-16}"; }

POSTGRES_USER="${POSTGRES_USER:-$(existing assistant-postgres POSTGRESQL_USER)}"; POSTGRES_USER="${POSTGRES_USER:-assistant}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(existing assistant-postgres POSTGRESQL_PASSWORD)}"; POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(rand 16)}"
POSTGRES_DB="${POSTGRES_DB:-$(existing assistant-postgres POSTGRESQL_DATABASE)}"; POSTGRES_DB="${POSTGRES_DB:-assistant}"
# Object store (VersityGW) credentials: the S3 access key and secret, also the web UI login
S3_ACCESS_KEY="${S3_ACCESS_KEY:-$(existing assistant-object-store S3_ACCESS_KEY)}"; S3_ACCESS_KEY="${S3_ACCESS_KEY:-assistant}"
S3_SECRET_KEY="${S3_SECRET_KEY:-$(existing assistant-object-store S3_SECRET_KEY)}"; S3_SECRET_KEY="${S3_SECRET_KEY:-$(rand 20)}"
N8N_ENCRYPTION_KEY="${N8N_ENCRYPTION_KEY:-$(existing assistant-n8n N8N_ENCRYPTION_KEY)}"; N8N_ENCRYPTION_KEY="${N8N_ENCRYPTION_KEY:-$(rand 32)}"
# n8n owner account, created by the chart's n8n-setup Job; the password needs a capital and a digit
N8N_OWNER_EMAIL="${N8N_OWNER_EMAIL:-$(existing assistant-n8n N8N_OWNER_EMAIL)}"; N8N_OWNER_EMAIL="${N8N_OWNER_EMAIL:-admin@example.com}"
N8N_OWNER_PASSWORD="${N8N_OWNER_PASSWORD:-$(existing assistant-n8n N8N_OWNER_PASSWORD)}"; N8N_OWNER_PASSWORD="${N8N_OWNER_PASSWORD:-Aa1$(rand 10)}"
LIVEKIT_API_KEY="${LIVEKIT_API_KEY:-$(existing assistant-livekit LIVEKIT_API_KEY)}"; LIVEKIT_API_KEY="${LIVEKIT_API_KEY:-APIk$(rand 6)}"
LIVEKIT_API_SECRET="${LIVEKIT_API_SECRET:-$(existing assistant-livekit LIVEKIT_API_SECRET)}"; LIVEKIT_API_SECRET="${LIVEKIT_API_SECRET:-$(rand 24)}"
QDRANT_API_KEY="${QDRANT_API_KEY:-$(existing assistant-qdrant QDRANT_API_KEY)}"; QDRANT_API_KEY="${QDRANT_API_KEY:-$(rand 24)}"
# Google service account for transcript archival: the JSON key file, or its content
if [ -n "${GOOGLE_SERVICE_ACCOUNT_FILE:-}" ]; then
  [ -r "${GOOGLE_SERVICE_ACCOUNT_FILE}" ] || { echo "GOOGLE_SERVICE_ACCOUNT_FILE ${GOOGLE_SERVICE_ACCOUNT_FILE} is not readable"; exit 1; }
  GOOGLE_SERVICE_ACCOUNT_JSON="$(cat "${GOOGLE_SERVICE_ACCOUNT_FILE}")"
fi
GOOGLE_SERVICE_ACCOUNT_JSON="${GOOGLE_SERVICE_ACCOUNT_JSON:-$(existing assistant-integrations GOOGLE_SERVICE_ACCOUNT_JSON)}"

make_secret() {
  local name="$1"; shift
  if oc get secret "${name}" -n "${NS}" >/dev/null 2>&1 && [ "${FORCE:-0}" != "1" ] \
     && ! printf ',%s,' "${REFRESH:-}" | grep -q ",${name},"; then
    echo "keep    ${name} (already exists; REFRESH=${name} rewrites it, FORCE=1 rewrites all)"
    return
  fi
  local verb=created; oc get secret "${name}" -n "${NS}" >/dev/null 2>&1 && verb="rewrote"
  oc create secret generic "${name}" -n "${NS}" "$@" --dry-run=client -o yaml | oc apply -f - >/dev/null
  echo "${verb} ${name}"
}

oc get namespace "${NS}" >/dev/null

make_secret assistant-postgres \
  --from-literal=POSTGRESQL_USER="${POSTGRES_USER}" \
  --from-literal=POSTGRESQL_PASSWORD="${POSTGRES_PASSWORD}" \
  --from-literal=POSTGRESQL_DATABASE="${POSTGRES_DB}" \
  --from-literal=DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"

make_secret assistant-object-store \
  --from-literal=S3_ACCESS_KEY="${S3_ACCESS_KEY}" \
  --from-literal=S3_SECRET_KEY="${S3_SECRET_KEY}"

make_secret assistant-n8n \
  --from-literal=N8N_ENCRYPTION_KEY="${N8N_ENCRYPTION_KEY}" \
  --from-literal=N8N_OWNER_EMAIL="${N8N_OWNER_EMAIL}" \
  --from-literal=N8N_OWNER_PASSWORD="${N8N_OWNER_PASSWORD}"

# Optional: used when qdrant.apiKeySecret is set in the chart values.
make_secret assistant-qdrant \
  --from-literal=QDRANT_API_KEY="${QDRANT_API_KEY}"

make_secret assistant-livekit \
  --from-literal=LIVEKIT_API_KEY="${LIVEKIT_API_KEY}" \
  --from-literal=LIVEKIT_API_SECRET="${LIVEKIT_API_SECRET}"

# API keys for model endpoints. In-cluster vLLM ignores them; MaaS endpoints need them.
make_secret assistant-models \
  --from-literal=LLM_API_KEY="${LLM_API_KEY:-none}" \
  --from-literal=STT_API_KEY="${STT_API_KEY:-none}" \
  --from-literal=TTS_API_KEY="${TTS_API_KEY:-none}" \
  --from-literal=EMBEDDINGS_API_KEY="${EMBEDDINGS_API_KEY:-none}" \
  --from-literal=GUARDRAILS_API_KEY="${GUARDRAILS_API_KEY:-none}" \
  --from-literal=HF_TOKEN="${HF_TOKEN:-}"

# External integrations. Leave empty to disable a feature.
make_secret assistant-integrations \
  --from-literal=SLACK_BOT_TOKEN="${SLACK_BOT_TOKEN:-}" \
  --from-literal=SIMLI_API_KEY="${SIMLI_API_KEY:-}" \
  --from-literal=SIMLI_FACE_ID="${SIMLI_FACE_ID:-}" \
  --from-literal=TAVUS_API_KEY="${TAVUS_API_KEY:-}" \
  --from-literal=TAVUS_FACE_ID="${TAVUS_FACE_ID:-}" \
  --from-literal=TAVUS_PAL_ID="${TAVUS_PAL_ID:-}" \
  --from-literal=GOOGLE_SERVICE_ACCOUNT_JSON="${GOOGLE_SERVICE_ACCOUNT_JSON:-}" \
  --from-literal=GOOGLE_DOCS_FOLDER_ID="${GOOGLE_DOCS_FOLDER_ID:-}"

echo
echo "Secrets are in namespace ${NS}. Back up assistant-n8n: losing N8N_ENCRYPTION_KEY makes the credentials stored in n8n unreadable."
echo "n8n owner: ${N8N_OWNER_EMAIL} (password: oc extract secret/assistant-n8n -n ${NS} --keys=N8N_OWNER_PASSWORD --to=-)"
